# Generated by Django 6.0.2 on 2026-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(default='TEMP1234', max_length=15),
            preserve_default=False,
        ),
    ]
